short_name = "blazium"
name = "Blazium Engine"
major = 4
minor = 3
patch = 0
status = "stable"
module_config = ""
website = "https://blazium.app"
docs = "4.3"
external_major = 0
external_minor = 4
external_patch = 0
external_status = "dev"
external_sha = "701abb87f2681c73dd2013e44b99d325209b40c7"
mirror_list = "https://blazium.app/api/mirrorlist/"
version_url = "https://blazium.app/api/versions-" + external_status + ".json"
