short_name = "blazium"
name = "Blazium Engine"
major = 4
minor = 3
patch = 0
status = "stable"
module_config = ""
website = "https://blazium.app"
docs = "4.3"
external_major = 0
external_minor = 3
external_patch = 0
external_status = "nightly"
external_sha = "da62c719004772ff4b59046711bc56899800e6e3"
mirror_list = "https://blazium.app/api/mirrorlist/"
version_url = "https://blazium.app/api/versions-" + external_status + ".json"
