#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_crowdcontrol = env_modules.Clone()

# Add all .cpp files in the module root
env_crowdcontrol.add_source_files(env.modules_sources, "*.cpp")

# Add editor files only when building for editor
if env.editor_build:
    env_crowdcontrol.add_source_files(env.modules_sources, "editor/*.cpp")
