#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env.Append(CPPPATH=["thirdparty"])

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(env_thirdparty.modules_sources, "#thirdparty/giflib/*.c")

env_gif = env_modules.Clone()

env_gif.add_source_files(env.modules_sources, "src/*.cpp")
env_gif.add_source_files(env.modules_sources, "src/editor/*.cpp")
env_gif.add_source_files(env.modules_sources, "*.cpp")
