#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_ircclient = env_modules.Clone()

# Module source files
env_ircclient.add_source_files(env.modules_sources, "*.cpp")

# Twitch IRC support
env_ircclient.add_source_files(env.modules_sources, "twitch/*.cpp")

# Optional mbedtls support for SSL/TLS
if env["module_mbedtls_enabled"]:
    env_ircclient.Append(CPPDEFINES=["MODULE_MBEDTLS_ENABLED"])

